### PR TITLE
Print FMUException on error for deviation example

### PR DESCRIPTION
**Pull request by jschueller**
it is useful to print the FMUException: for example the error when the runtime is not available
I don't know why we exit instead of (re)raising exceptions though (that's why nosetests exits silently and it's bad, or at least it should exit with an error code != 0 for ci to fail), so I left it as-is

what do you think @SG-phimeca ?

### CODE REVIEW

**Comment by jschueller** [comment]
@SG-phimeca on Travis, with ubuntu trusty and conda, at the end of nosetests the interpreter crashes:
```Elapsed simulation time: 0.4196900000000028 seconds.
..
----------------------------------------------------------------------
Ran 2 tests in 244.842s
OK
*** Error in `/home/travis/miniconda/bin/python': free(): invalid pointer: 0x00007f2a92182975 ***
/home/travis/build.sh: line 62:  9977 Aborted                 (core dumped) nosetests --nocapture```

**Comment by SG-phimeca** [comment]
@jschueller The error handling is indeed rudimentary. However, note that the IndexError is most likely raised by an exotic platform while the FMUException could be raised either because the FMU is indeed absent or by some other, possibly more preoccupying, failure. This example was initial meant as a demo instead of test, hence the graceful exit.

**Comment by jschueller** [comment]
Ok, I changed this to not catch FMUException anymore. What about the segfault ?

**Comment by SG-phimeca** [comment]
As far as I know, the segfault is caused by bug in pyfmi.

**Comment by jschueller** [comment]
A known bug ? Did you encounter it on your box ?

**Comment by SG-phimeca** [comment]
I tracked down a few situation ending in segfaults. I'll have to check 
if it's one of them. Reporting them is on my todo list. Some other 
segfaults have been already reported by, see for instance 
http://www.jmodelica.org/27813.

**Comment by jschueller** [comment]
@SG-phimeca I propose to not run tests on Linux for now (windows is tested), but this remains an important bug!
You can merge it if you agree.

**Comment by jschueller** [comment]
ping @SG-phimeca

**Comment by SG-phimeca** [comment]
This is indeed a serious problem (segfault :see_no_evil: ) but little can be done *now*.

**Pull request closed without merging**
