### PR TITLE
Run tests in win/py3, enable linux tests

### PR DESCRIPTION
**Pull request by jschueller**
Just for test, do not merge

### CODE REVIEW

**Comment by jschueller** [comment]
@SG-phimeca We can see the tests still fail on linux.
We also see a syntax error in bil100.py missing a parenthesis.

**Comment by jschueller** [comment]
What version of openmodelica did you use ? I guess a very recent one:
https://github.com/OpenModelica/OMCompiler/commit/86c322678972ec0b248bbb214ded0ce71dbd1ed0

**Comment by jschueller** [comment]
Works on linux with openmodelica nightly!

**Comment by SG-phimeca** [comment]
I currently use the nightly build : 1.12.0~dev-482-g510e895-1
I hoped that using a recent version would solve the dependence of the FMUs on openmodelica.

**Comment by jschueller** [comment]
Nope, it still requires openmodelica.

**Comment by SG-phimeca** [comment]
Indeed. I assume this is a bug on their part. I'll file it as soon as possible.

**Comment by jschueller** [comment]
But maybe it's a bit dangerous to rely on nightly, I propose to stick to stable if possible.

**Pull request merged**
